{
 "title": "Relational Database Service (RDS)",
 "description": "【Huawei Cloud RDS Monitoring Metrics Description】https://support.huaweicloud.com/usermanual-rds/rds_06_0001.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "Enterprise Project", "query": { "query": "huaweicloud_epinfo" } },
   {
    "name": "hostIP",
    "label": "RDS-IP",
    "query": {
     "query": "label_values(huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\"},dataVip)"
    }
   },
   {
    "name": "hostname",
    "label": "Instance Name",
    "query": {
     "query": "label_values(huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\",dataVip=~\"$hostIP\"},name)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview ( Enterprise Project ) Enterprise Project : $EPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "EPS"
  },
  {
   "title": "RDS Resource Overview Table 【 Enterprise Project : $EPS , Total Instances : $total 】",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds001_cpu_util{epId=~\"$EPS\"} -0",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "huaweicloud_sys_rds_rds002_mem_util{epId=~\"$EPS\"} -0",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "huaweicloud_sys_rds_rds039_disk_util{epId=~\"$EPS\"} - 0",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds006_conn_count{epId=~'$EPS'}) by (dataVip) - 0",
     "legendFormat": "Total Connection Count"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds004_bytes_in{epId=~'$EPS'}) by (dataVip) - 0",
     "legendFormat": "Network Input Throughput"
    },
    {
     "expr": "avg(huaweicloud_sys_rds_rds005_bytes_out{epId=~'$EPS'}) by (dataVip) - 0",
     "legendFormat": "Network Output Throughput"
    }
   ]
  },
  {
   "title": "Resource Details：【 $EPS 】【 $hostIP 】【 $hostname 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "EPS"
  },
  {
   "title": "CPU Usage Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds001_cpu_util{dataVip=~\"$hostIP\"}",
     "legendFormat": "{{dataVip}}({{name}})-CPU Usage Rate"
    }
   ]
  },
  {
   "title": "Memory Usage Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds002_mem_util{dataVip=~\"$hostIP\"}",
     "legendFormat": "{{dataVip}}({{name}})Memory Usage Rate"
    }
   ]
  },
  {
   "title": "QPS+TPS",
   "type": "graph",
   "description": "QPS: This metric is used to count the number of SQL statement queries, including stored procedures, in queries per second.\nTPS: This metric is used to count the number of transactions executed, including both commits and rollbacks, in transactions per second.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds008_qps{dataVip=~\"$hostIP\"}",
     "legendFormat": "{{dataVip}}({{name}})-QPS"
    },
    {
     "expr": "huaweicloud_sys_rds_rds009_tps{dataVip=~\"$hostIP\"}",
     "legendFormat": "{{dataVip}}({{name}})-TPS"
    }
   ]
  },
  {
   "title": "Disk Usage Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds039_disk_util{dataVip=~\"$hostIP\"}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Usage Rate(/)"
    }
   ]
  },
  {
   "title": "Disk I/O Usage Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds081_vm_ioutils{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk I/O Usage Rate(/)"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate (IOPS)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds003_iops{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Read IOPS"
    }
   ]
  },
  {
   "title": "Disk Read/Write Throughput",
   "type": "graph",
   "description": "Read bytes Number of bytes read per second per disk partition\nWritten bytes Number of bytes written per second per disk partition",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-)/Write (+)" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds049_disk_read_throughput{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Read Throughput"
    },
    {
     "expr": "huaweicloud_sys_rds_rds050_disk_write_throughput{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Write Throughput"
    }
   ]
  },
  {
   "title": "Disk Read/Write Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds075_avg_disk_ms_per_read{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Read"
    },
    {
     "expr": "huaweicloud_sys_rds_rds076_avg_disk_ms_per_write{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Write"
    }
   ]
  },
  {
   "title": "Replication Delay (Average + Realtime)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds073_replication_delay{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Realtime Replication Delay"
    },
    {
     "expr": "huaweicloud_sys_rds_rds173_replication_delay_avg{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Average Replication Delay"
    }
   ]
  },
  {
   "title": "Disk Read/Write Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-)/Write (+)" }
   ],
   "targets": [
    {
     "expr": "0 - huaweicloud_sys_rds_rds049_disk_read_throughput{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Read Throughput"
    },
    {
     "expr": "huaweicloud_sys_rds_rds050_disk_write_throughput{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Disk Write Throughput"
    }
   ]
  },
  {
   "title": "Number of Slow Log Entries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds074_slow_queries{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Number of Slow Log Entries"
    }
   ]
  },
  {
   "title": "Network Connection Information",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "huaweicloud_sys_rds_rds006_conn_count{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Total Number of Database Connections"
    },
    {
     "expr": "huaweicloud_sys_rds_rds007_conn_active_count{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Current Active Connections"
    },
    {
     "expr": "huaweicloud_sys_rds_rds072_conn_usage{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Connection Usage Rate"
    },
    {
     "expr": "huaweicloud_sys_rds_rds_conn_active_usage{dataVip=~'$hostIP'}",
     "legendFormat": "{{dataVip}}({{name}})-Active Connection Usage Rate"
    }
   ]
  }
 ]
}